// Copyright 2023-2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//
// Source: model.go in package mockcreds
// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -source /home/vgonzla/kubernetes/eks-irsa-agent/pkg/credentials/model.go -package mockcreds
//
// Package mockcreds is a generated GoMock package.
package mockcreds

import (
	context "context"
	reflect "reflect"

	credentials "go.amzn.com/eks/eks-pod-identity-agent/pkg/credentials"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialRetriever is a mock of CredentialRetriever interface.
type MockCredentialRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRetrieverMockRecorder
}

// MockCredentialRetrieverMockRecorder is the mock recorder for MockCredentialRetriever.
type MockCredentialRetrieverMockRecorder struct {
	mock *MockCredentialRetriever
}

// NewMockCredentialRetriever creates a new mock instance.
func NewMockCredentialRetriever(ctrl *gomock.Controller) *MockCredentialRetriever {
	mock := &MockCredentialRetriever{ctrl: ctrl}
	mock.recorder = &MockCredentialRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRetriever) EXPECT() *MockCredentialRetrieverMockRecorder {
	return m.recorder
}

// GetIamCredentials mocks base method.
func (m *MockCredentialRetriever) GetIamCredentials(ctx context.Context, request *credentials.EksCredentialsRequest) (*credentials.EksCredentialsResponse, credentials.ResponseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIamCredentials", ctx, request)
	ret0, _ := ret[0].(*credentials.EksCredentialsResponse)
	ret1, _ := ret[1].(credentials.ResponseMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIamCredentials indicates an expected call of GetIamCredentials.
func (mr *MockCredentialRetrieverMockRecorder) GetIamCredentials(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIamCredentials", reflect.TypeOf((*MockCredentialRetriever)(nil).GetIamCredentials), ctx, request)
}

// MockResponseMetadata is a mock of ResponseMetadata interface.
type MockResponseMetadata struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMetadataMockRecorder
}

// MockResponseMetadataMockRecorder is the mock recorder for MockResponseMetadata.
type MockResponseMetadataMockRecorder struct {
	mock *MockResponseMetadata
}

// NewMockResponseMetadata creates a new mock instance.
func NewMockResponseMetadata(ctrl *gomock.Controller) *MockResponseMetadata {
	mock := &MockResponseMetadata{ctrl: ctrl}
	mock.recorder = &MockResponseMetadataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseMetadata) EXPECT() *MockResponseMetadataMockRecorder {
	return m.recorder
}

// AssociationId mocks base method.
func (m *MockResponseMetadata) AssociationId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociationId")
	ret0, _ := ret[0].(string)
	return ret0
}

// AssociationId indicates an expected call of AssociationId.
func (mr *MockResponseMetadataMockRecorder) AssociationId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociationId", reflect.TypeOf((*MockResponseMetadata)(nil).AssociationId))
}
